version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Jamaica"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["dependencies", "github-actions"]
