-- Tellinex baseline extractor
--
-- Produces the contents of 20260403000000_baseline_prod_schema_dump_6may2026.sql
-- by scanning pg_catalog. Run this against any Postgres 17 Supabase project to
-- re-generate the baseline:
--
--   psql "$CONN" -f _extractor.sql       -- creates the helper functions
--   psql "$CONN" -tA -c                  \
--     "SELECT public._tx_dump_public_schema()" \
--     > baseline.sql                     -- write the dump
--   psql "$CONN" -c                      \
--     "DROP FUNCTION public._tx_dump_public_schema(); \
--      DROP FUNCTION public._tx_table_ddl(OID);"      -- cleanup
--
-- Or just call _tx_dump_public_schema() directly from any tool that can
-- execute SQL with superuser privileges (Supabase MCP `execute_sql`, etc.)
-- and INSERT the result into supabase_migrations.schema_migrations.

-- ---------------------------------------------------------------------------
-- Per-table CREATE TABLE builder
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public._tx_table_ddl(rel_oid OID) RETURNS TEXT
LANGUAGE plpgsql AS $fn$
DECLARE
  coldefs TEXT := '';
  col RECORD;
  v_schema TEXT;
  v_name  TEXT;
BEGIN
  SELECT n.nspname, c.relname INTO v_schema, v_name
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE c.oid = rel_oid;

  FOR col IN
    SELECT a.attname,
           format_type(a.atttypid, a.atttypmod) AS coltype,
           a.attnotnull,
           pg_get_expr(d.adbin, d.adrelid) AS defval,
           a.attidentity, a.attgenerated
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
    WHERE a.attrelid = rel_oid AND a.attnum>0 AND NOT a.attisdropped
    ORDER BY a.attnum
  LOOP
    coldefs := coldefs || format(E'  %I %s', col.attname, col.coltype);
    IF col.attidentity = 'a' THEN
      coldefs := coldefs || ' GENERATED ALWAYS AS IDENTITY';
    ELSIF col.attidentity = 'd' THEN
      coldefs := coldefs || ' GENERATED BY DEFAULT AS IDENTITY';
    ELSIF col.attgenerated = 's' AND col.defval IS NOT NULL THEN
      coldefs := coldefs || format(' GENERATED ALWAYS AS (%s) STORED', col.defval);
    ELSIF col.defval IS NOT NULL THEN
      coldefs := coldefs || format(' DEFAULT %s', col.defval);
    END IF;
    IF col.attnotnull THEN
      coldefs := coldefs || ' NOT NULL';
    END IF;
    coldefs := coldefs || E',\n';
  END LOOP;

  RETURN format(E'CREATE TABLE IF NOT EXISTS %I.%I (\n%s\n);',
                v_schema, v_name, rtrim(coldefs, E',\n'));
END
$fn$;

-- ---------------------------------------------------------------------------
-- Master extractor: emits the whole public-schema baseline as TEXT
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public._tx_dump_public_schema() RETURNS TEXT
LANGUAGE plpgsql AS $fn$
DECLARE
  ddl TEXT := '';
  rec RECORD;
  ext_oids OID[];
BEGIN
  ddl := E'-- Tellinex prod public-schema baseline (auto-generated via pg_catalog introspection)\n';
  ddl := ddl || E'-- Generated: ' || now()::text || E'\n';
  ddl := ddl || E'-- Server: PostgreSQL 17.6 / project egztpclpcnizcdtfugsv\n';
  ddl := ddl || E'-- Method: pg_catalog scan (pg_dump 17 unavailable: client is v16, no DB credentials)\n\n';

  SELECT COALESCE(array_agg(objid), ARRAY[]::oid[]) INTO ext_oids
  FROM pg_depend WHERE deptype='e';

  -- Extensions
  ddl := ddl || E'-- =========\n-- Extensions\n-- =========\n';
  FOR rec IN
    SELECT extname, n.nspname
    FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace
    WHERE extname <> 'plpgsql'
    ORDER BY extname
  LOOP
    ddl := ddl || format(E'CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;\n',
                         rec.extname, rec.nspname);
  END LOOP;
  ddl := ddl || E'\n';

  -- Non-default schemas
  ddl := ddl || E'-- =======\n-- Schemas\n-- =======\n';
  FOR rec IN
    SELECT nspname FROM pg_namespace
    WHERE nspname NOT IN ('public','auth','storage','pg_catalog','information_schema',
                          'pg_toast','extensions','vault','realtime','graphql',
                          'graphql_public','pgsodium','pgsodium_masks','net',
                          'supabase_migrations','supabase_functions','_realtime',
                          'pgmq','pgbouncer','cron','_analytics')
      AND nspname NOT LIKE 'pg_%'
    ORDER BY nspname
  LOOP
    ddl := ddl || format(E'CREATE SCHEMA IF NOT EXISTS %I;\n', rec.nspname);
  END LOOP;
  ddl := ddl || E'\n';

  -- Standalone sequences (excluding identity-backing)
  ddl := ddl || E'-- =========\n-- Sequences\n-- =========\n';
  FOR rec IN
    SELECT n.nspname, c.relname,
           s.seqstart, s.seqincrement, s.seqmin, s.seqmax, s.seqcache, s.seqcycle
    FROM pg_class c
    JOIN pg_namespace n ON n.oid=c.relnamespace
    JOIN pg_sequence s ON s.seqrelid=c.oid
    WHERE c.relkind='S' AND n.nspname='public'
      AND NOT (c.oid = ANY(ext_oids))
      AND NOT EXISTS (SELECT 1 FROM pg_depend d
                      WHERE d.objid=c.oid AND d.deptype IN ('a','i'))
    ORDER BY n.nspname, c.relname
  LOOP
    ddl := ddl || format(
      E'CREATE SEQUENCE IF NOT EXISTS %I.%I START %s INCREMENT %s MINVALUE %s MAXVALUE %s CACHE %s%s;\n',
      rec.nspname, rec.relname, rec.seqstart, rec.seqincrement,
      rec.seqmin, rec.seqmax, rec.seqcache,
      CASE WHEN rec.seqcycle THEN ' CYCLE' ELSE ' NO CYCLE' END);
  END LOOP;
  ddl := ddl || E'\n';

  -- Tables (with RLS toggles)
  ddl := ddl || E'-- ======\n-- Tables\n-- ======\n';
  FOR rec IN
    SELECT c.oid, n.nspname, c.relname, c.relrowsecurity, c.relforcerowsecurity
    FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE c.relkind='r' AND n.nspname='public' AND NOT (c.oid = ANY(ext_oids))
    ORDER BY c.relname
  LOOP
    ddl := ddl || public._tx_table_ddl(rec.oid) || E'\n';
    IF rec.relrowsecurity THEN
      ddl := ddl || format(E'ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY;\n',
                           rec.nspname, rec.relname);
    END IF;
    IF rec.relforcerowsecurity THEN
      ddl := ddl || format(E'ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY;\n',
                           rec.nspname, rec.relname);
    END IF;
  END LOOP;
  ddl := ddl || E'\n';

  -- Constraints (PK, UNIQUE, CHECK, FK) — wrapped for idempotency
  ddl := ddl || E'-- ===========\n-- Constraints\n-- ===========\n';
  FOR rec IN
    SELECT con.conname, n.nspname, c.relname,
           pg_get_constraintdef(con.oid) AS def, con.contype
    FROM pg_constraint con
    JOIN pg_class c ON c.oid=con.conrelid
    JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND con.contype IN ('p','u','c','f')
      AND NOT (con.oid = ANY(ext_oids))
    ORDER BY CASE con.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 WHEN 'f' THEN 4 END,
             c.relname, con.conname
  LOOP
    ddl := ddl || format(
      E'DO $idem$ BEGIN ALTER TABLE %I.%I ADD CONSTRAINT %I %s; EXCEPTION WHEN duplicate_object OR duplicate_table OR unique_violation THEN NULL; END $idem$;\n',
      rec.nspname, rec.relname, rec.conname, rec.def);
  END LOOP;
  ddl := ddl || E'\n';

  -- Indexes (excluding ones backing constraints)
  ddl := ddl || E'-- =======\n-- Indexes\n-- =======\n';
  FOR rec IN
    SELECT i.indexrelid, c.relname, n.nspname,
           pg_get_indexdef(i.indexrelid) AS def, i.indisunique
    FROM pg_index i
    JOIN pg_class c ON c.oid=i.indexrelid
    JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND NOT (c.oid = ANY(ext_oids))
      AND NOT EXISTS (SELECT 1 FROM pg_constraint con
                      WHERE con.conindid=i.indexrelid)
    ORDER BY c.relname
  LOOP
    IF rec.indisunique THEN
      ddl := ddl || regexp_replace(rec.def, '^CREATE UNIQUE INDEX ',
                                   'CREATE UNIQUE INDEX IF NOT EXISTS ', 'i') || E';\n';
    ELSE
      ddl := ddl || regexp_replace(rec.def, '^CREATE INDEX ',
                                   'CREATE INDEX IF NOT EXISTS ', 'i') || E';\n';
    END IF;
  END LOOP;
  ddl := ddl || E'\n';

  -- Functions (skip our own helpers)
  ddl := ddl || E'-- =========\n-- Functions\n-- =========\n';
  FOR rec IN
    SELECT pg_get_functiondef(p.oid) AS def
    FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='public' AND NOT (p.oid = ANY(ext_oids))
      AND p.proname NOT IN ('_tx_table_ddl','_tx_dump_public_schema')
    ORDER BY p.oid
  LOOP
    ddl := ddl || rec.def || E';\n\n';
  END LOOP;

  -- Views (creation order)
  ddl := ddl || E'-- =====\n-- Views\n-- =====\n';
  FOR rec IN
    SELECT n.nspname, c.relname, pg_get_viewdef(c.oid, true) AS def
    FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE c.relkind='v' AND n.nspname='public' AND NOT (c.oid = ANY(ext_oids))
    ORDER BY c.oid
  LOOP
    ddl := ddl || format(E'CREATE OR REPLACE VIEW %I.%I AS\n%s\n',
                         rec.nspname, rec.relname, rec.def);
  END LOOP;
  ddl := ddl || E'\n';

  -- Triggers
  ddl := ddl || E'-- ========\n-- Triggers\n-- ========\n';
  FOR rec IN
    SELECT t.tgname, n.nspname, c.relname, pg_get_triggerdef(t.oid) AS def
    FROM pg_trigger t
    JOIN pg_class c ON c.oid=t.tgrelid
    JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND NOT t.tgisinternal AND NOT (t.oid = ANY(ext_oids))
    ORDER BY c.relname, t.tgname
  LOOP
    ddl := ddl || format(E'DROP TRIGGER IF EXISTS %I ON %I.%I;\n',
                         rec.tgname, rec.nspname, rec.relname);
    ddl := ddl || rec.def || E';\n';
  END LOOP;
  ddl := ddl || E'\n';

  -- Event triggers (those whose function lives in public)
  ddl := ddl || E'-- ==============\n-- Event triggers\n-- ==============\n';
  FOR rec IN
    SELECT e.evtname, e.evtevent,
           quote_ident(np.nspname) || '.' || quote_ident(p.proname) AS funcname
    FROM pg_event_trigger e
    JOIN pg_proc p ON p.oid=e.evtfoid
    JOIN pg_namespace np ON np.oid=p.pronamespace
    WHERE np.nspname='public' AND NOT (e.oid = ANY(ext_oids))
    ORDER BY e.evtname
  LOOP
    ddl := ddl || format(E'DROP EVENT TRIGGER IF EXISTS %I;\n', rec.evtname);
    ddl := ddl || format(E'CREATE EVENT TRIGGER %I ON %s EXECUTE FUNCTION %s();\n',
                         rec.evtname, rec.evtevent, rec.funcname);
  END LOOP;
  ddl := ddl || E'\n';

  -- Policies
  ddl := ddl || E'-- ========\n-- Policies\n-- ========\n';
  FOR rec IN
    SELECT schemaname, tablename, policyname, permissive, roles, cmd, qual, with_check
    FROM pg_policies WHERE schemaname='public'
    ORDER BY tablename, policyname
  LOOP
    ddl := ddl || format(E'DROP POLICY IF EXISTS %I ON %I.%I;\n',
                         rec.policyname, rec.schemaname, rec.tablename);
    ddl := ddl || format(
      E'CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;\n',
      rec.policyname, rec.schemaname, rec.tablename,
      rec.permissive, rec.cmd, array_to_string(rec.roles, ', '),
      CASE WHEN rec.qual IS NOT NULL
           THEN E'\n  USING (' || rec.qual || ')' ELSE '' END,
      CASE WHEN rec.with_check IS NOT NULL
           THEN E'\n  WITH CHECK (' || rec.with_check || ')' ELSE '' END);
  END LOOP;
  ddl := ddl || E'\n';

  ddl := ddl || E'-- End of baseline\n';
  RETURN ddl;
END
$fn$;
